### ISSUE TITLE
No way to save preferences? Awesome ldapInfoShow  1.0

### ISSUE THREAD

**Issue by Ticogrande** [wangvisual/ldapinfo#23]
Using Thunderbird 31.6.0.  I am trying to change preferences to NOT use all email address.  I uncheck them... but then there is no "Save" button to save the changes.  Am I losing my marbles??  How do I save the changes?

**Comment by Ticogrande** [comment]
By the way... just closing Preferences does not save the changes.

**Comment by wangvisual** [comment]
Please use this version
https://github.com/wangvisual/ldapinfo/blob/master/beta/ldapinfo-1.1-tb.xpi
Thanks.

**Comment by Ticogrande** [comment]
Working.  Thanks
